spring.application.name=backend3
server.port=${PORT:8080}

# =========================
# NEON POSTGRESQL (TEMPORARY TESTING)
# =========================
spring.datasource.url=jdbc:postgresql://ep-super-glitter-aog5v2e1-pooler.c-2.ap-southeast-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_bH0sZErFv7Cy
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata

# =========================
# FILE UPLOAD
# =========================
easyfish.upload-dir=uploads

# =========================
# AWS S3 (KEEP EMPTY FOR NOW)
# =========================
aws.s3.enabled=true
aws.s3.region=ap-south-1
aws.s3.bucket=
aws.s3.public-url=
aws.s3.access-key=
aws.s3.secret-key=
aws.s3.presign-expiry-seconds=900

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# =========================
# JWT
# =========================
jwt.secret=easyfish-testing-secret-key
jwt.expiration=86400000

# =========================
# MAIL
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# =========================
# ADMIN MAIL
# =========================
easyfish.admin-order-email.enabled=true
easyfish.admin-order-email.to=nabhasyafoods01@gmail.com

# =========================
# RAZORPAY
# =========================
razorpay.enabled=true
razorpay.key-id=
razorpay.key-secret=
razorpay.webhook.secret=

# =========================
# FAST2SMS
# =========================
fast2sms.api-key=
fast2sms.route=otp
fast2sms.sender-id=
fast2sms.template-id=

# =========================
# GOOGLE LOGIN
# =========================
google.client-id=
google.client-secret=

# =========================
# TIMEZONE
# =========================
spring.jackson.time-zone=Asia/Kolkata

# =========================
# PROXY
# =========================
server.forward-headers-strategy=framework

# =========================
# CORS
# =========================
cors.allowed-origins=https://easyfish.in,https://www.easyfish.in,https://easyfish-store.netlify.app,https://easyfish-admin.netlify.app,https://easyfish-backend.onrender.com,http://localhost:3000,http://localhost:3001
